ignore:
  # Spring Boot Application file - no testable logic
  - "**/Application.java"
  # SpringBootRequestHandler -  no testable logic
  - "**/LoadDiscreteGroundWaterHandler.java"
  # Spring Properties POJO -  no testable logic
  - "**/Properties.java"