spring:
  datasource-transform:
    url: jdbc:postgresql://${TRANSFORM_DATABASE_ADDRESS}:${TRANSFORM_DATABASE_PORT}/${TRANSFORM_DATABASE_NAME}?currentSchema=${TRANSFORM_SCHEMA_NAME}
    username: ${TRANSFORM_SCHEMA_OWNER_USERNAME}
    password: ${TRANSFORM_SCHEMA_OWNER_PASSWORD}
    hikari:
      maximum-pool-size: 2
  datasource-observation:
    url: jdbc:postgresql://${OBSERVATION_DATABASE_ADDRESS}:${OBSERVATION_DATABASE_PORT}/${OBSERVATION_DATABASE_NAME}?currentSchema=${OBSERVATION_SCHEMA_NAME}
    username: ${OBSERVATION_SCHEMA_OWNER_USERNAME}
    password: ${OBSERVATION_SCHEMA_OWNER_PASSWORD}
    hikari:
      maximum-pool-size: 2
      auto-commit: false
  properties:
    snsTopicArn: ${ATQS_CAPTURE_SNS_LOG_ARN}

logging:
  level:
    root: ${ROOT_LOG_LEVEL}
    com.zaxxer: OFF
